name: Run E2E
jobs:
  - path: action_templates/jobs/setup.yaml
    if: github.event.pull_request.head.repo.full_name == 'mongodb/mongodb-kubernetes-operator'
    steps:
      - cancel-previous
      - checkout
      - setup-and-install-python
      - quay-login
      - build-and-push-development-images

events:
  - on-pull-request-master
  - on-push-master
  - workflow-dispatch
