name: Run Single E2E
jobs:
  - path: setup
    steps:
    - checkout
    - setup-and-install-python
    - quay-login
    - build-and-push-development-images
  - path: single-test
    steps:
    - checkout
    - setup-and-install-python
    - setup-kind-cluster
    - run-test-single
    - dump-and-upload-diagnostics-always

events:
  - single-e2e-workflow-dispatch
